SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SSIS_OJNadredjeni] (
		[OJ_KOOP]                        [varchar](50) COLLATE SQL_Croatian_CP1250_CI_AS NULL,
		[AVIZO_SIFRA_NADREDJENOG_OJ]     [bigint] NULL
)
GO
ALTER TABLE [dbo].[SSIS_OJNadredjeni] SET (LOCK_ESCALATION = TABLE)
GO
